# Generated by Django 3.1.7 on 2021-07-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
