# Generated by Django 3.1.7 on 2021-07-16 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=100)),
                ('topic_image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('meta_description', models.CharField(max_length=255)),
                ('meta_keywords', models.CharField(max_length=255)),
                ('background_image', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('is_publish', models.CharField(choices=[(1, 'publish'), (0, 'draft')], default=0, max_length=10)),
                ('slug', models.CharField(default='<django.db.models.fields.CharField>', max_length=130)),
                ('timeStamp', models.DateField(blank=True)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.topic')),
            ],
        ),
    ]
