# Generated by Django 3.1.7 on 2021-07-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_publish',
            field=models.CharField(choices=[('p', 'publish'), ('d', 'draft')], default='d', max_length=10),
        ),
    ]
